### ISSUE TITLE
Support Latex and AsciiMath formats for Mathematical equations

### ISSUE THREAD

**Issue by manavmanocha** [comprodls/marked#7]
Per @gauravchaddha 

Currently in order to render Math Equations in Courseware, we have to write MathML directly into markdown. MathML is very verbose and cannot be written directly by the author. Latex on the other hand is something which (though tough) could be written by the author in mark down directly.

Allow other formats (Tex or may be AsciiMath in future). This will allow flexibility to write content in markdown in Author’s preferred format (and not force require latex to mathml conversion while authoring)

**Comment by manavmanocha** [comment]
@nalinchhibber ..Please proceed with following steps
1. Define Markdown grammar for Latex/AsciiMath and update wiki
2. Implement and release

**Comment by gauravchaddha** [comment]
Following are the points that I will like to add (this is the information I have, might be useful) -  
MathML is an output format. It is not designed to be written directly, but it is designed to be read. Latex could be though of an Input format used for authoring. Conversion from Latex to MathML can be done on the fly via javascrpting. 
There are library files available for different format. So if your HTML contains math, these libraries will find math equations and convert them to mathml format for browser to paint.
Mathjax is one such library. It does allow rendering of math (latex) into web browser. Mathjax Library is already included in the Courseware app, however I believe it needs to be configured appropriately to support this. Checkout the possible configurations here - http://docs.mathjax.org/en/latest/config-files.html.
Seems like currently MML_CHTML configuration is being used.
